# AUTOGENERATED! DO NOT EDIT! File to edit: Solution.ipynb.

# %% auto 0
__all__ = []

# %% Solution.ipynb 9
from datetime import datetime

import streamlit as st

from streamlit_jupyter import StreamlitPatcher, tqdm
sp = StreamlitPatcher()
sp.jupyter()  # register patcher with streamlit

# %% Solution.ipynb 10
st.title("Example")

# %% Solution.ipynb 11
st.markdown(
    """

This is a test page demonstrating the use of `streamlit_jupyter`.

If you're seeing this in jupyter, then it's working!

"""
)

# %% Solution.ipynb 12
name = st.text_input("What's your name?", "John")

# %% Solution.ipynb 13
date = st.date_input("Choose a date", datetime.now().date())

# %% Solution.ipynb 14
st.markdown(f"## Hello {name}!\n## The date is {date.strftime('%Y-%m-%d')}")

# %% Solution.ipynb 15
st.subheader("Data Editor")
df = pd.DataFrame(
    [
        {
            "command": "st.selectbox",
            "rating": 4,
            "is_widget": True,
        },
        {
            "command": "st.balloons",
            "rating": 5,
            "is_widget": False,
        },
        {
            "command": "st.time_input",
            "rating": 3,
            "is_widget": True,
        },
    ]
)
edited_df = st.experimental_data_editor(df)

# %% Solution.ipynb 16
st.subheader("Ploting")

import plotly.express as px

df_daily = df[["rating"]].mean(axis="columns").rename("daily_average")
fig = px.line(df_daily, title="Daily mean", width=600)
st.write(fig)

# %% Solution.ipynb 17
options = st.multiselect(
    "Multiselect with defaults: ",
    options=["nbdev", "streamlit", "jupyter", "fastcore"],
    default=["jupyter", "streamlit"],
)

# %% Solution.ipynb 18
st.subheader("st.text:")
st.text("This is a text")
st.text("This is \n multiline text")
st.code("This is multiline \n code", language=None)
